### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [fcontreras18/weekone#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by fcontreras18** [comment]
Thanks Billy, fixed it! I'm also going to try to figure out a way to hide "Here's the best unsolicited jiu jitsu advice you can get!" on mobile devices to make it less cluttered.

Thanks,
Francisco

**Comment by BillyMassey** [comment]
Good Job!
